In [1]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
v1 = np.array([[1,2]])
v2 = np.array([[2,4]])
v3 = np.array([[-1,-2]])

In [4]:
# v1 and v3 are opposite --> Low

# v1 and v2 are similar --> High

In [5]:
cosine_similarity(v1,v2)

array([[1.]])

In [6]:
cosine_similarity(v1,v3)

array([[-1.]])

In [7]:
cosine_similarity(v3,v2)

array([[-1.]])

In [8]:
from sentence_transformers import SentenceTransformer

In [ ]:
#  AI model - all-MiniLM-L6-V2

In [ ]:
# from typing import ValuesView
# when we provide any text it will store in form of embeddings
# vectors
# vectors means numbers
# how many numbers : 384 values
# apple : 384 Values
# eat an apple : 384 values

In [9]:
sentences = ["cat sleep on sofa",
             'virat has age 37 years old',
             'capital of India is Delhi',
             'Trump is president of USA']

In [10]:
model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [11]:
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [12]:
embeddings = model.encode(sentences)

In [13]:
embeddings

array([[ 0.1470197 , -0.06850552, -0.0266373 , ...,  0.04750449,
         0.0432121 ,  0.00415207],
       [ 0.02213954,  0.11032011, -0.01575185, ..., -0.08253331,
         0.08669701,  0.04003426],
       [ 0.06552516,  0.01266835, -0.03874186, ...,  0.01148091,
         0.04636326,  0.0387023 ],
       [ 0.08163679,  0.00633773,  0.05628716, ..., -0.00425824,
         0.14550938,  0.02793589]], dtype=float32)

In [14]:
len(embeddings)


4

In [15]:
embeddings[0]

array([ 1.47019699e-01, -6.85055181e-02, -2.66373008e-02,  2.47730277e-02,
        1.23438863e-02,  4.98519987e-02, -1.15255751e-02, -2.18097046e-02,
        1.44700157e-02,  5.82495295e-02, -9.26762894e-02,  3.33766155e-02,
        1.47126941e-02,  9.70975980e-02, -3.75856049e-02,  4.24654447e-02,
       -7.97572136e-02, -2.90175080e-02,  6.85152039e-02,  7.12183341e-02,
        3.00763594e-03,  2.50531659e-02,  6.03636056e-02, -5.51803745e-02,
       -2.71780882e-02, -1.16433948e-02, -1.28765879e-02, -8.46974105e-02,
       -2.72812489e-02,  2.23780684e-02, -3.40605490e-02, -4.69545610e-02,
       -4.08335440e-02, -8.81199632e-03, -1.35337363e-03, -3.94067764e-02,
       -7.56383548e-03, -1.12342630e-02, -6.70332909e-02,  1.59317002e-01,
       -6.88800262e-03, -2.51380540e-02,  4.60509071e-03, -4.25988398e-02,
       -3.55689414e-02,  1.84286712e-03, -1.07436478e-02, -7.57930279e-02,
        4.43793945e-02,  4.16952819e-02, -6.09958209e-02,  1.08900247e-02,
       -3.29329148e-02, -

In [16]:
len(embeddings[0])

384

In [17]:
v1 = embeddings[0]
v2 = embeddings[1]
v3 = embeddings[2]
v4 = embeddings[3]

In [18]:
question = "What is age of virat"

In [19]:
qv = model.encode(question)

In [20]:
len(qv)

384

In [21]:
qv

array([ 2.69927625e-02,  1.42622590e-01, -1.09004090e-02, -4.39866036e-02,
       -4.84335124e-02,  6.01310767e-02, -4.38825749e-02,  6.34727776e-02,
       -1.17552951e-01,  5.94387315e-02,  7.50527084e-02, -7.07089975e-02,
        9.85561591e-03, -1.62683520e-02,  6.40304573e-03, -3.47382762e-02,
        5.10217659e-02, -1.15564547e-03,  3.63188647e-02, -5.48212267e-02,
       -2.26784777e-02,  1.85926016e-02,  4.47867736e-02, -4.94241416e-02,
        1.70731172e-02,  2.88831107e-02, -1.56579748e-01,  2.32104082e-02,
        6.69281334e-02,  2.61805672e-02,  2.60500051e-02,  3.99135835e-02,
        1.56107238e-02,  6.23652153e-02, -2.07281578e-02, -8.70964080e-02,
       -2.28692498e-02,  2.05054749e-02, -1.21817775e-01,  1.04480565e-01,
       -6.97716251e-02, -5.50231384e-03, -6.75618798e-02, -1.75358467e-02,
        2.84310915e-02, -2.78380364e-02, -2.49396823e-02,  5.44983847e-03,
        8.58341623e-03,  7.16149583e-02, -8.89229402e-02, -4.71932963e-02,
        4.65846285e-02,  

In [22]:
v1.shape

(384,)

In [23]:
qv.shape

(384,)

In [24]:
cosine_similarity([v1],[qv])

array([[-0.00792735]], dtype=float32)

In [25]:
cosine_similarity([v2],[qv])

array([[0.8866191]], dtype=float32)

In [26]:
cosine_similarity([v3],[qv])

array([[-0.01900897]], dtype=float32)

In [27]:
cosine_similarity([v4],[qv])

array([[-0.03620929]], dtype=float32)

In [ ]:
# v2 has a high score === sentence 2 is answer